spring:
  application:
    name: dubbo-provider
nacos:
  server-address: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
dubbo:
  application:
    name: dubbo-provider
  scan:
    base-packages: xyz.bolitao.provider.service
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
#    address: N/A
